version: "3.8"

services:
  multiplayer:
    container_name: mach-moto-server
    build: .
    ports:
      - 127.0.0.1:3333:3333
    restart: unless-stopped
    environment:
      - PORT=3333
      - NODE_ENV=production
